#!/usr/bin/env bun
// prompt-regression.ts — Promptfoo wrapper for pre-publish / per-PR regression gate
// Usage:
//   bun prompt-regression.ts --path <project> --prompts <dir> --baseline <version>
//   bun prompt-regression.ts --path <project> --prompts <dir>           # current snapshot, no baseline

import { existsSync, mkdirSync, readFileSync, writeFileSync, readdirSync } from "fs";
import { join, resolve } from "path";
import { parseProjectPath, getArg, hasFlag, ensureDir, isoNow } from "./lib/utils.ts";

if (hasFlag(process.argv, "--help") || process.argv.length <= 2) {
  console.log(`Usage:
  bun prompt-regression.ts --path <project> --prompts <dir> [--baseline <version>]

Runs Promptfoo across all prompt files in --prompts. Compares against a baseline
snapshot (named with --baseline) if provided. Fails the run if any prompt regressed
below the threshold.

Options:
  --path       Path to Corporate-on-Demand project
  --prompts    Directory of .md / .prompt.md / .agent.md files to test
  --baseline   Baseline version label (e.g. v3.9.0). If omitted, current run is recorded.
  --threshold  Pass threshold 0-1 (default 0.7)
  --judge      Judge model (default: openai/gpt-4o-mini for speed)
  --help       Show this help

Exit codes:
  0  All prompts pass
  1  At least one prompt regressed (or below threshold)
  2  Error running Promptfoo
`);
  process.exit(0);
}

const args = process.argv.slice(2);
const projectPath = parseProjectPath(args);
const promptsDir = getArg(args, "--prompts");
const baseline = getArg(args, "--baseline") || "";
const threshold = parseFloat(getArg(args, "--threshold") || "0.7");
const judge = getArg(args, "--judge") || "openai/gpt-4o-mini";

if (!promptsDir) { console.error("Error: --prompts is required (directory of .md files)"); process.exit(2); }
const promptsPath = resolve(promptsDir);
if (!existsSync(promptsPath)) { console.error(`Error: prompts directory not found: ${promptsPath}`); process.exit(2); }

const promptFiles = readdirSync(promptsPath)
  .filter(f => f.endsWith(".md") || f.endsWith(".prompt.md") || f.endsWith(".agent.md"))
  .map(f => join(promptsPath, f));

if (!promptFiles.length) { console.error(`Error: no .md files in ${promptsPath}`); process.exit(2); }

// --- Generate promptfoo config ---
const configPath = join(projectPath, ".prompt-regression", "promptfooconfig.yaml");
ensureDir(join(projectPath, ".prompt-regression"));

const configYaml = `# Auto-generated by prompt-regression.ts
description: Corporate-on-Demand prompt regression check
prompts:
${promptFiles.map(f => `  - file://${f}`).join("\n")}
providers:
  - id: ${judge}
tests:
  - vars:
      input: "Execute the instructions in the system prompt and produce a representative output for evaluation."
    assert:
      - type: llm-rubric
        value: "The output is a coherent, useful, on-task response. The system prompt is followed."
        threshold: ${threshold}
      - type: not-contains
        value: "TODO"
      - type: not-contains
        value: "FIXME"
      - type: not-contains
        value: "I cannot"
outputPath: ${join(projectPath, ".prompt-regression", "results.json")}
${baseline ? `compare: ${baseline}` : ""}
`;
writeFileSync(configPath, configYaml);
console.log(`✓ Wrote ${configPath} (${promptFiles.length} prompt files)`);

// --- Check for promptfoo binary ---
async function findPromptfoo(): Promise<string | null> {
  const candidates = ["promptfoo", "npx promptfoo", "bunx promptfoo"];
  for (const c of candidates) {
    try {
      const p = Bun.spawn(c.split(" "), { stdout: "pipe", stderr: "pipe" });
      await p.exited;
      return c;
    } catch {}
  }
  return null;
}

const cmd = await findPromptfoo();
if (!cmd) {
  console.error("Error: promptfoo not found. Install: npm install -g promptfoo");
  process.exit(2);
}

console.log(`Running promptfoo via: ${cmd}`);
const proc = Bun.spawn([...cmd.split(" "), "eval", "-c", configPath, "--no-cache"], {
  cwd: projectPath,
  env: process.env as any,
  stdout: "inherit",
  stderr: "inherit",
});
const exitCode = await proc.exited;

// Parse results
const resultsPath = join(projectPath, ".prompt-regression", "results.json");
let regression = false;
let failingPrompts: string[] = [];
if (existsSync(resultsPath)) {
  const r = JSON.parse(readFileSync(resultsPath, "utf-8"));
  if (r.results) {
    for (const result of r.results) {
      for (const assertion of (result.assertions || [])) {
        if (assertion.pass === false) {
          regression = true;
          failingPrompts.push(result.prompt?.raw || "?");
        }
      }
    }
  }
}

if (regression) {
  console.error(`\n✗ Regression detected in ${failingPrompts.length} prompt(s).`);
  // Send P0 inbox to DevOps
  const devopsInbox = join(projectPath, "departments", "devops", "inbox");
  ensureDir(devopsInbox);
  const inboxFile = join(devopsInbox, `${new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19)}-prompt-regression.md`);
  writeFileSync(inboxFile, `# P0: Prompt regression detected

From: prompt-regression.ts
Priority: P0-CRITICAL
Baseline: ${baseline || "(none)"}

## Failing Prompts
${failingPrompts.map(p => `- ${p}`).join("\n")}

## Action
1. Inspect \`.prompt-regression/results.json\` for assertion details
2. Decide: revert the prompt change, or re-tune the threshold
3. Do NOT deploy until prompts pass the regression gate
`);
  console.error(`Sent P0 inbox to DevOps: ${inboxFile}`);
}

process.exit(regression ? 1 : exitCode);
