#!/usr/bin/env bun
// prompt-optimize.ts — DSPy wrapper for iterative prompt improvement
// Usage:
//   bun prompt-optimize.ts --path <project> --action init --task <name> --examples <jsonl>
//   bun prompt-optimize.ts --path <project> --action run  --task <name> --metric <name> --budget <n>
//   bun prompt-optimize.ts --path <project> --action status
//   bun prompt-optimize.ts --path <project> --action archive --task <name> --version <n>
//
// DSPy + GEPA drive the "revisit and re-improve" loop. This script:
//   1. init  — generate programs/<task>/optimize.py + programs/<task>/data/ from examples
//   2. run   — spawn `uv run --with dspy python optimize.py`, write result to confluence/workflows/
//   3. status — list all optimization runs and their scores
//   4. archive — move old versioned prompts into programs/_archive/

import { existsSync, mkdirSync, readFileSync, writeFileSync, readdirSync } from "fs";
import { join, resolve } from "path";
import { parseProjectPath, getArg, getArgList, hasFlag, ensureDir, isoNow } from "./lib/utils.ts";

if (hasFlag(process.argv, "--help") || process.argv.length <= 2) {
  console.log(`Usage:
  bun prompt-optimize.ts --path <project> --action init --task <name> --examples <jsonl>
  bun prompt-optimize.ts --path <project> --action run  --task <name> --metric <name> --budget <n>
  bun prompt-optimize.ts --path <project> --action status
  bun prompt-optimize.ts --path <project> --action archive --task <name> --version <n>

Actions:
  init     Generate DSPy program skeleton + copy examples
  run      Run GEPA optimization, write best prompt to confluence/workflows/
  status   List all optimization runs and their scores
  archive  Move old versioned prompt into programs/_archive/

Options:
  --path      Path to Corporate-on-Demand project
  --action    One of: init | run | status | archive
  --task      Task name (e.g. devops-dm, rnd-pitch, qa-checklist)
  --examples  Path to JSONL training examples (init only)
  --metric    Metric name (run only). Default: deepeval_geval
  --budget    GEPA trial budget (run only). Default: 200
  --version   Version to archive (archive only, e.g. v1, v2)
  --judge     Judge model. Default: openai/deepseek-chat (override for OpenAI, Anthropic, etc.)
  --help      Show this help`);
  process.exit(0);
}

const args = process.argv.slice(2);
const projectPath = parseProjectPath(args);
const action = getArg(args, "--action");

if (!action || !["init", "run", "status", "archive"].includes(action)) {
  console.error("Error: --action must be one of: init | run | status | archive");
  process.exit(1);
}

const task = getArg(args, "--task");
const programsDir = join(projectPath, "programs");
const workflowsDir = join(projectPath, "confluence", "workflows");
const taskDir = task ? join(programsDir, task) : null;

function ensurePythonDeps(): void {
  // Quick sanity check. Real check happens when the spawned process fails.
  // We don't fail here because uv resolves deps per-invocation.
  if (!existsSync(join(projectPath, "pyproject.toml")) && !existsSync(join(projectPath, "requirements.txt"))) {
    // Not an error — uv run --with resolves per-package. Just a soft hint.
    console.log("Note: no pyproject.toml or requirements.txt at project root. Using `uv run --with dspy` per invocation.");
  }
}

function programTemplate(taskName: string, examplesPath: string): string {
  return `#!/usr/bin/env python3
"""DSPy program for ${taskName} — auto-generated by prompt-optimize.ts.

Run: uv run --with dspy-ai --with deepeval optimize.py

This program:
  1. Loads examples from ${examplesPath}
  2. Defines a Signature (input → output fields)
  3. Compiles with the GEPA optimizer using a DeepEval-based metric
  4. Saves the best prompt to ./optimized_prompt.json
"""
import json
import os
import sys
from pathlib import Path

import dspy
from dspy.teleprompt import GEPA

EXAMPLES_PATH = Path("${examplesPath}")
JUDGE_MODEL = os.environ.get("DSPY_JUDGE_MODEL", "openai/deepseek-chat")
BUDGET = int(os.environ.get("DSPY_BUDGET", "200"))

# --- Configure LM ---
lm = dspy.LM(JUDGE_MODEL)
dspy.configure(lm=lm)

# --- Load examples ---
def load_examples(path: Path) -> list[dspy.Example]:
    if not path.exists():
        print(f"ERROR: examples file not found: {path}", file=sys.stderr)
        sys.exit(1)
    examples = []
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line:
            continue
        data = json.loads(line)
        ex = dspy.Example(**data).with_inputs(*data.keys())
        examples.append(ex)
    return examples

# --- Signature (CUSTOMIZE THIS for your task) ---
class ${taskName.replace(/-/g, "_").title().replace(/_/g, "")}Task(dspy.Signature):
    """${taskName} task signature.

    TODO: Replace this docstring + fields with the actual task you want optimized.
    """
    situation = dspy.InputField(desc="Describe the situation requiring this task")
    # TODO: add your actual output fields
    output = dspy.OutputField(desc="Generated output for this task")

# --- Module ---
class ${taskName.replace(/-/g, "_").title().replace(/_/g, "")}Module(dspy.Module):
    def __init__(self):
        super().__init__()
        self.predict = dspy.Predict(${taskName.replace(/-/g, "_").title().replace(/_/g, "")}Task)

    def forward(self, **kwargs):
        return self.predict(**kwargs)

# --- Metric (DEEVEVAL_BRIDGE) ---
# This wraps a DeepEval GEval metric. The custom_metric below must match
# the rubric in your DeepEval config.
def metric(example, pred, trace=None) -> float:
    """Score 0-1 via DeepEval GEval. Replace with your own GEval instance."""
    try:
        from deepeval.metrics import GEval
        from deepeval.test_case import LLMTestCase, LLMTestCaseParams

        # CUSTOMIZE: build the test case from example + pred
        test_case = LLMTestCase(
            input=str(example.situation),
            actual_output=str(pred.output),
            # expected_output=str(example.expected_output) if hasattr(example, "expected_output") else None,
        )

        g_eval = GEval(
            name="${taskName}_quality",
            criteria="The output is high quality for ${taskName}.",  # CUSTOMIZE
            evaluation_params=[LLMTestCaseParams.INPUT, LLMTestCaseParams.ACTUAL_OUTPUT],
        )
        g_eval.measure(test_case)
        return g_eval.score / 10.0  # GEval returns 0-10, normalize to 0-1
    except Exception as e:
        print(f"metric error: {e}", file=sys.stderr)
        return 0.0

# --- Optimize ---
def main():
    examples = load_examples(EXAMPLES_PATH)
    print(f"Loaded {len(examples)} examples from {EXAMPLES_PATH}")

    # 80/20 train/test split
    split = int(len(examples) * 0.8)
    trainset = examples[:split]
    devset = examples[split:]
    print(f"Train: {len(trainset)}, Dev: {len(devset)}")

    module = ${taskName.replace(/-/g, "_").title().replace(/_/g, "")}Module()
    optimizer = GEPA(metric=metric, auto="medium", budget=BUDGET)

    print(f"Running GEPA optimization with budget={BUDGET}...")
    compiled = optimizer.compile(module, trainset=trainset)

    # Evaluate on dev set
    score = 0.0
    for ex in devset:
        pred = compiled(**{k: getattr(ex, k) for k in ex.inputs().keys()})
        score += metric(ex, pred)
    avg_score = score / max(len(devset), 1)
    print(f"Dev set score: {avg_score:.3f}")

    # Save the optimized program + extract the prompt
    compiled.save("./optimized_program.json")
    with open("./optimized_prompt.json", "w") as f:
        json.dump({
            "task": "${taskName}",
            "score": avg_score,
            "budget": BUDGET,
            "judge_model": JUDGE_MODEL,
            "instructions": compiled.predict.signature.instructions if hasattr(compiled, "predict") else "",
            "examples_count": len(examples),
            "timestamp": "${isoNow()}",
        }, f, indent=2)
    print(f"Saved optimized_prompt.json (score={avg_score:.3f})")

if __name__ == "__main__":
    main()
`;
}

function initAction(): void {
  if (!task) { console.error("Error: --task is required for init"); process.exit(1); }
  const examples = getArg(args, "--examples");
  if (!examples) { console.error("Error: --examples is required for init (path to JSONL)"); process.exit(1); }

  const examplesSrc = resolve(examples);
  if (!existsSync(examplesSrc)) { console.error(`Error: examples file not found: ${examplesSrc}`); process.exit(1); }

  ensureDir(taskDir!);
  const dataDir = join(taskDir!, "data");
  ensureDir(dataDir);
  const examplesDest = join(dataDir, "examples.jsonl");
  writeFileSync(examplesDest, readFileSync(examplesSrc, "utf-8"));

  const programPath = join(taskDir!, "optimize.py");
  writeFileSync(programPath, programTemplate(task, examplesDest));

  console.log(`✓ Initialized ${task} at ${taskDir}`);
  console.log(`  Examples: ${examplesDest}`);
  console.log(`  Program:  ${programPath}`);
  console.log(`Next: edit ${programPath} to define your Signature's input/output fields and metric criteria, then run --action run.`);
}

async function runAction(): Promise<void> {
  if (!task) { console.error("Error: --task is required for run"); process.exit(1); }
  const optimizePy = join(taskDir!, "optimize.py");
  if (!existsSync(optimizePy)) { console.error(`Error: no program at ${optimizePy}. Run --action init first.`); process.exit(1); }

  const metric = getArg(args, "--metric") || "deepeval_geval";
  const budget = getArg(args, "--budget") || "200";
  const judge = getArg(args, "--judge") || "openai/deepseek-chat";

  ensurePythonDeps();
  ensureDir(workflowsDir);

  const env: Record<string, string> = { ...process.env as any, DSPY_JUDGE_MODEL: judge, DSPY_BUDGET: budget };

  console.log(`Running GEPA optimization for task '${task}' (judge=${judge}, budget=${budget})...`);
  const proc = Bun.spawn(["uv", "run", "--with", "dspy-ai", "--with", "deepeval", "python", optimizePy], {
    cwd: taskDir!,
    env,
    stdout: "inherit",
    stderr: "inherit",
  });
  const exitCode = await proc.exited;
  if (exitCode !== 0) { console.error(`DSPy optimization failed (exit ${exitCode})`); process.exit(exitCode); }

  const resultPath = join(taskDir!, "optimized_prompt.json");
  if (!existsSync(resultPath)) { console.error("Error: optimization did not produce optimized_prompt.json"); process.exit(1); }
  const result = JSON.parse(readFileSync(resultPath, "utf-8"));
  const score = result.score || 0;
  console.log(`\n✓ Optimization complete. Dev score: ${score.toFixed(3)}`);

  // Write to confluence/workflows/<task>.v<N>.md
  const existingVersions = readdirSync(workflowsDir)
    .filter(f => f.startsWith(`${task}.v`) && f.endsWith(".md"))
    .length;
  const version = `v${existingVersions + 1}`;
  const workflowPath = join(workflowsDir, `${task}.${version}.md`);
  const workflowContent = `# ${task} — ${version}

> Generated by DSPy GEPA optimizer via prompt-optimize.ts.
> Judge: ${result.judge_model}
> Score: ${result.score.toFixed(3)} (budget=${result.budget})
> Timestamp: ${result.timestamp}

## Optimized Instructions

${result.instructions || "(no instructions extracted)"}

## Metadata

- Examples used: ${result.examples_count}
- Judge model: ${result.judge_model}
- Dev set score: ${result.score.toFixed(3)}

## Next Steps

1. Run \`prompt-eval.ts --v1 <prev> --v2 ${workflowPath}\` to verify improvement
2. If v2 > v1 + threshold, send inbox to CEO for approval
3. On approval, promote ${workflowPath} → ${task}.md (canonical)
4. Archive the previous canonical to programs/_archive/
`;
  writeFileSync(workflowPath, workflowContent);
  console.log(`✓ Wrote ${workflowPath}`);

  // Send inbox to QA for verification
  const qaInbox = join(projectPath, "departments", "qa", "inbox");
  ensureDir(qaInbox);
  const inboxFile = join(qaInbox, `${new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19)}-${task}-${version}-verify.md`);
  writeFileSync(inboxFile, `# QA: Verify ${task} ${version}

From: prompt-optimize.ts
Priority: P2-MEDIUM

## What
DSPy GEPA produced ${version} of the ${task} prompt.

## Dev Set Score
${result.score.toFixed(3)} (judge: ${result.judge_model})

## Action
Run \`prompt-eval.ts\` to compare against the previous version and confirm improvement.

\`\`\`
bun $SCRIPTS/prompt-eval.ts --path <project> \\
  --v1 confluence/workflows/${task}.v${existingVersions || 1}.md \\
  --v2 ${workflowPath} \\
  --test-set ${join(taskDir!, "data", "examples.jsonl")} \\
  --threshold 0.05
\`\`\`
`);
  console.log(`✓ Sent inbox to QA: ${inboxFile}`);
}

function statusAction(): void {
  if (!existsSync(programsDir)) { console.log("No programs directory yet."); return; }
  const tasks = readdirSync(programsDir, { withFileTypes: true })
    .filter(d => d.isDirectory() && d.name !== "_archive")
    .map(d => d.name);
  if (!tasks.length) { console.log("No optimization tasks yet."); return; }
  for (const t of tasks) {
    const resultPath = join(programsDir, t, "optimized_prompt.json");
    if (existsSync(resultPath)) {
      const r = JSON.parse(readFileSync(resultPath, "utf-8"));
      console.log(`  ${t}: score=${r.score?.toFixed(3) || "?"} judge=${r.judge_model || "?"} timestamp=${r.timestamp || "?"}`);
    } else {
      console.log(`  ${t}: (no result yet)`);
    }
  }
}

function archiveAction(): void {
  if (!task) { console.error("Error: --task is required for archive"); process.exit(1); }
  const version = getArg(args, "--version");
  if (!version) { console.error("Error: --version is required for archive (e.g. v1)"); process.exit(1); }
  const src = join(workflowsDir, `${task}.${version}.md`);
  if (!existsSync(src)) { console.error(`Error: not found: ${src}`); process.exit(1); }
  const archiveDir = join(programsDir, "_archive", task);
  ensureDir(archiveDir);
  const dest = join(archiveDir, `${version}.md`);
  const content = readFileSync(src, "utf-8");
  writeFileSync(dest, content);
  // Don't delete from workflows/ — keep for history
  console.log(`✓ Archived ${src} → ${dest}`);
}

switch (action) {
  case "init": initAction(); break;
  case "run": await runAction(); break;
  case "status": statusAction(); break;
  case "archive": archiveAction(); break;
}
